### ISSUE TITLE
How to cancel effect and resume it later.

### ISSUE THREAD

**Issue by hazzo** [ngrx/platform#1103]
## Other information:
I'm trying to cancel an effect with the method `ngrxOnRunEffects`. I manage to cancel the effect and in consequence canceling a request (that is the main purpose of canceling this effect). But when user navigates to a new page the canceled effect won't be triggered again on a new action dispatch.
My goal is to cancel the effect and then on following navigations if action is dispatched resume the effect subscription.

This is the actual snippet of the code that I'm using for the `ngrxOnRunEffects` method:
```
  ngrxOnRunEffects(resolvedEffects$: Observable<EffectNotification>) {
     return resolvedEffects$.pipe(
      takeUntil(this.action$.pipe(ofType(commonActionsTypes.CANCEL_EFFECTS)))
     );
   }
```
I have this code on a particular Effects Class and I'm not looking for a action type.
I'm trying to understand the `ngrxOnRunEffects` implementation but I think I'm missing something.

Thanks for your help!

## I would be willing to submit a PR for the docs :heart:

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by tdeschryver** [comment]
Hi, this is because you're using `takeUntil` operator which won't emit a new value when the `Cancel_Effects` has been dispatched - see [docs](http://reactivex.io/documentation/operators/takeuntil.html). 

I'm going to close this issue because it isn't a bug, I'll be glad to help you out on our [gitter channel](https://gitter.im/ngrx/platform).
