### ISSUE TITLE
Issues upgrading to v4.0.0

### ISSUE THREAD

**Issue by alexjlockwood** [ngrx/platform#111]
When I follow the migration instructions and attempt to migrate [my project](https://github.com/alexjlockwood/ShapeShifter) to the new version of `@ngrx/store` I get the following errors. I can provide additional details if needed:

```
ERROR in /Users/alex/ShapeShifter/src/app/store/storefreeze/metareducer.ts (12,16): Property 'payload' does not exist on type 'Action'.

ERROR in /Users/alex/ShapeShifter/src/app/store/storefreeze/metareducer.ts (14,25): Property 'payload' does not exist on type 'Action'.

ERROR in /Users/alex/ShapeShifter/src/app/store/reducer.ts (56,28): Supplied parameters do not match any signature of call target.

ERROR in /Users/alex/ShapeShifter/src/app/store/reducer.ts (57,20): Supplied parameters do not match any signature of call target.

ERROR in /Users/alex/ShapeShifter/src/test/MockStore.ts (12,14): Class 'MockStore' incorrectly extends base class 'Store<StateWithHistoryAndTimestamp>'.
  Types of property 'select' are incompatible.
    Type '<R>(mapFn: any, ...paths: string[]) => Observable<R>' is not assignable to type '{ <K>(mapFn: (state: StateWithHistoryAndTimestamp) => K): Store<K>; <a extends "group" | "timesta...'.
      Type 'Observable<any>' is not assignable to type 'Store<any>'.
        Property 'actionsObserver' is missing in type 'Observable<any>'.

ERROR in /Users/alex/ShapeShifter/src/test/MockStore.ts (17,7): Argument of type 'Observer<Action>' is not assignable to parameter of type 'StateObservable'.
  Property '_isScalar' is missing in type 'Observer<Action>'.

ERROR in /Users/alex/ShapeShifter/src/test/MockStore.ts (24,12): Class 'Store<StateWithHistoryAndTimestamp>' defines instance member function 'select', but extended class 'MockStore' defines it as instance member property.
```

**Comment by malua** [comment]
Why would "Action" not define a property "payload" anymore?

**Comment by josh-sachs** [comment]
same issue - by the looks of it they may be trying to coerce people into using the toPayload utility function which simply casts action to <any> before returning...

https://github.com/ngrx/platform/blob/015107f88dc1713a33f7a7596791513985fd8e35/modules/effects/src/util.ts

**Comment by MikeRyanDev** [comment]
You will need to update your metareducer that freezes state. `payload` is no longer part of the `Action` interface as it introduced type safety issues.

**Comment by josh-sachs** [comment]
@MikeRyanDev can you elaborate?  You lost me at "metareducer that freezes state"

The docs reference toPayload, which really should be toPayload<T> if type saftey is the concern.

**Comment by josh-sachs** [comment]
the change appears to be a new expectation that each state reducer's action argument no longer be of type `Action` but instead be a concrete type implementing `Action`

https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions

This is not referenced anywhere in the migration doc from what I can tell. 

in 2.x
```
export function SomeReducerFunction(state: SomeState = SomeStateDefault, action: Action): SomeState {
...
}
```

in 4.x
```
export class SomeStateAction implements Action {
    type = "SomeStateAction"
    constructor(public payload: SomeState) { }
};

export function SomeReducerFunction(state: SomeState = SomeStateDefault, action: SomeStateAction): SomeState {
...
}
```

Its an interesting change, but definitely could have been implemented in a way that made migration less invasive - especially considering that the underlying implementation of Action remains unchanged. 

Overall I think this introduces a lot more scaffolding to the entire project.  The example I linked to even takes a shortcut by abandoning type-safety in the reducer function's signature... action is typed as `Action `instead of something concrete like `Increment`.  In the body of each case statement, I think you would actually need to re-cast the Action back to its concrete type since you aren't using instanceof in order to determine the context of the action, but rather just a string property - I haven't tried it so not 100% sure.

**Comment by littleStudent** [comment]
Just a comment about the type safety.
> abandoning type-safety in the reducer function's signature

This is not true. Typescript can handle the type through the `switch case`.
It will only give you the types of the specific action.

**Comment by josh-sachs** [comment]
as i mentioned - i hadn't actually tried it, but that is impressive considering there is no constraint on the type property to guarantee its uniqueness.

**Comment by alexjlockwood** [comment]
@josh-sachs You should use [discriminated union](https://www.typescriptlang.org/docs/handbook/advanced-types.html) types if you want type safety in your reducers. Check out the example app in this repo for an example on how to set it up.

**Comment by alexjlockwood** [comment]
@josh-sachs Even better, there is a section about it in the docs: https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions

**Comment by cozzbie** [comment]
Thats just waaaaayyy to much bootstrap code just to get this done. I had to revert to v2.2.3. That suits us just foine!!!
