### ISSUE TITLE
Is store observable always emits 'undefined' value on init?

### ISSUE THREAD

**Issue by KaidenAlenko2017** [ngrx/platform#1127]
I am writing a function to fetch language resources from the server.

Basically, I defined an AppStore and defines the languages variables inside this store

# AppStore.ts
```
export interface AppStore {
      languages: any[];
}
```

Then, I defines a LanguageServices to call the HTTP request. The constructor of LanguageServices as follows.

# LanguageServices .ts
```
  languages: Observable <any[]>;
  constructor
  (
    http: HttpService,
    private store: Store<AppStore>
  ) {
    this.languages = store.select('languages');
  }
```

To fetch language, I defines a function getLanguage() in LanguageServices. The getLanguage() function sends an httpRequest and dispatch LanguageAction.FETCH_LANGUAGE action afterwards.

# LanguageServices .ts
```
getLanguage(lan) {
   this.http.post(apiURL, obj)
            .map((res) => {
                return res || {};
            })
            .map((payload) => {
                return {type: LanguageAction.FETCH_LANGUAGE, payload : payload};
            }).subscribe(action => this.store.dispatch(action));
  }
```

All works fine and the languages is now stores in the store.

# LanguageButton.ts
I use an component to get language, this component has a button when people clicks on this button, it will use getLanguage(lan) to dispatch action.
```

 constructor(
    private langService: LanguageService,
    private store: Store <AppStore>,
  ) {
      this.lang = this.langService.languages;
      this.allDataFetched = true;
  }

```

I subscribe to this language observable to see whats inside the observable. It did get the languages result. However, After subscribe, it emits values for two times.

# LanguageButton.ts
```
this.lang.subscribe( data => {
        console.log(this.lang);
      });

```
1st time : 'undefined' (onNgInit)
2nd time : the language object (after clicks the button)

I was wondering is this is the normal behavior of the observable in store. Why does the observable emits 'undefined' on init? Shouldn't it emits nothing instead?

I would like to show this component after the languages is fetched, however, since it emits 'undefined' at start, It cannot do this unless I check " this.lang = 'undefined' " at the subscription.

**Comment by tdeschryver** [comment]
Hi this is working as intended.
That's why in mostly every reducer example that you can find there will be an `initialState` - see the [NgRx seed](https://stackblitz.com/edit/ngrx-seed?embed=1&file=src/app/reducers/counter.reducer.ts) or the [example app](https://stackblitz.com/github/ngrx/platform/tree/61cbfe537f9df8cef3dd4a6ee0b8f483e49653f4?file=example-app%2Fapp%2Fbooks%2Freducers%2Fbooks.ts).

There are several ways to 'bootstrap' an NgRx app with initial state (state hydration with a meta-reducer, providing an initial state in `StoreModule.forRoot`, ...) - if you need some more info or help you can always as for feedback or guidance in our [gitter channel](https://gitter.im/ngrx/platform).

**Comment by ShevaDavid** [comment]
I suspect there is some memory leak in the example app, because my CPU became crazy when I opened Stackblitz
