### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by sylvaingirardbe** [ngrx/platform#1147]
I was writing a test for an effect without dispatch and the toHaveBeenCalled expectation kept failing on me. I followed the way it is done in the example app (collection.effect.spec.ts, `describe('openDB$' )`) except I used the `provideMockActions` provider for the actions.
Anyway, it kept failing until it dawned on me that the expectation was run before the observable emitted. Moving the expectation into the subscribe fixed the problem.

I didn't run the tests in the example app to see if it behaves the same way but I presume that the behavior is a bit random. Moving the expectation into the subscribe makes it more stable, it seems.

## Other information:
This would be my suggestion:
 ```
 describe('openDB$', () => {
    it('should call db.open when initially subscribed to', () => {
      effects.openDB$.subscribe(() => 
        expect(db.open).toHaveBeenCalledWith('books_app')
      );
    });
  });
```

## I would be willing to submit a PR for the docs :heart:
Yes

**Comment by brandonroberts** [comment]
The test in [collection.effect.spec.ts](https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/collection.effects.spec.ts#L42) works correctly. It may be due to a difference in your effect. Have you verified that the expectation is actually running inside the subscribe with ` done` callback?
