### ISSUE TITLE
Sidenav closes with Esc

### ISSUE THREAD

**Issue by maghidini** [ngrx/platform#1172]
Once you open the sidenav and closes it with Esc, after there is no way to re-open it, since the action `LayoutActions.OpenSidenav()` hasn't been dispatched. One quick fix is adding attribute `disableClose` on `mat-sidenav` element into `sidenav.component.ts` leaving: 
`<mat-sidenav [opened]="open" disableClose>`

**Comment by tdeschryver** [comment]
Hi @maghidini, are you willing to open a PR with your fix? 😄

**Comment by manklu** [comment]
The following material sample contains anything needed to capture escape and backdrop click to dispatch the close event.
https://stackblitz.com/angular/nnoxoxrlemx?file=app%2Fsidenav-disable-close-example.html

Altenatively you can listen to the openedChange event.
https://material.angular.io/components/sidenav/api

**Comment by mgred** [comment]
Hi all,
I took on this bug (hope nobody worked on it in the meanwhile).

The example linked by @manklu looks nice, but cannot be easily applied into the code as far as I can say. This is due to the fact that you need `mat-sidenav` and `mat-sidenav-content` to be in one component, as stated [here](https://github.com/angular/material2/issues/8959).

I created #1244 which fixed this by applying `disableClose` as @maghidini already suggested and inserted a manual closing mechanism with `(keydown.escape)="sidenav.close()"`. Also the action `CloseSidenav` is fired.

**Comment by maghidini** [comment]
Looks good to me 👍
