### ISSUE TITLE
Add documentation on combineReducers

### ISSUE THREAD

**Issue by anth-git** [ngrx/platform#1179]
Why there is no mention in documentation about combineReducers function? 
Is it deprecated or what?
In redux world it seem to be quite popular approach to break complex reducers into smaller ones. 
I know that there is ActionReducerMap but, if I'm not mistaken it is for combining feature reducers into root reducer. What I want to do is to break my feature reducer into smaller reducers, that handle slice of feature state.

**Comment by mgred** [comment]
Hey @anth-git,
The `combineReducers` function is not depreciated. It is a common technique used in redux and explained in detail [here](https://redux.js.org/api-reference/combinereducers).
The only difference in the function provided by `@ngrx/store` is, that it takes an `initialState` argument as second parameter.

**Comment by tdeschryver** [comment]
Like @mgred mentioned the `combineReducers` function is not deprecated. 
It's used internally within the ngrx/store when you use `StoreModule.forRoot` or `StoreModule.forFeature`, that's why you probably won't need it (and isn't documented).

For example:
If you declare your reducers as:
```
export const reducers = {
  foo: fooReducer,
  bar: barReducer,
};
```

And pass this reducer object when you import the store module:
```
StoreModule.forRoot(reducers),
```

The reducers object will be passed to the `combineReducers` function.

It is mentioned in the example app [app.module.ts#L42](https://github.com/ngrx/platform/blob/master/example-app/app/app.module.ts#L42).

**Comment by brandonroberts** [comment]
As @tdeschryver mentioned, you probably won't need it. If you want to provide your own version of `combineReducers`, you can always override the built-in one with the `reducerFactory` configuration option which is not documented also.

**Comment by jyotendra** [comment]
Its not deprecated but seems like using combineReducers hinders with [AOT](https://github.com/ngrx/platform/blob/master/docs/store/api.md#feature-module-reducers-and-aot)

**Comment by whisher** [comment]
Hi there,
considering that I didn't find any example,
I post this simple one
`import { combineReducers } from '@ngrx/store';

import {
  userAddressesReducer,
  UserAddressesState,
  initialUserAddressesState
} from './user-addresses.reducer';
import { userProfileReducer, UserProfileState, initialUserProfileState } from './user-profile.reducer';

export interface UserState {
  addresses: UserAddressesState;
  profile: UserProfileState;
}

export const initialUserState: UserState = {
  addresses: initialUserAddressesState,
  profile: initialUserProfileState,
};

export const userReducer = combineReducers(
  {
    addresses: userAddressesReducer,
    profile: userProfileReducer
  },
  initialUserState
);
`

**Comment by samyue** [comment]
I wonder why the documentation for combineReducers is missing?  I need combineReducers for a two level structure, so some common code logic can be reused. CombineReducers is really important for more complex real world problems

**Comment by Maximaximum** [comment]
It's really pity that this function has not been documented yet. In my app, I need a multilevel reducer tree, to break complex state handling into multiple reducers. This is not achievable via `StoreModule.forFeature()`, because it only lets to register top-level child reducers - this does not help with multilevel scenarios.
