### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by atodd-geoplan** [ngrx/platform#1245]
Is there any reason fro you to promote the use of uppercase const names in your documentation even though it goes against the ng style guide for new code?

https://angular.io/guide/styleguide#style-03-02

**Comment by timdeschryver** [comment]
I'm sure @brandonroberts or @MikeRyanDev have something to say on this.
But I think it's because of and "old" convention, to define const types in order to quickly notice that it's a const.

Also, I also like how the Angular docs are putting it:

> Why? The tradition of naming constants in UPPER_SNAKE_CASE reflects an era before the modern IDEs that quickly reveal the const declaration. TypeScript prevents accidental reassignment.
Do tolerate existing const variables that are spelled in UPPER_SNAKE_CASE.
Why? The tradition of UPPER_SNAKE_CASE remains popular and pervasive, especially in third party modules. It is rarely worth the effort to change them at the risk of breaking existing code and documentation.

**Comment by atodd-geoplan** [comment]
@timdeschryver but the use of a 3rd party library is no longer 3rd party - it is new code.

Thus i believe the example code and documentation should follow the style guide.

**Comment by timdeschryver** [comment]
If this is how you can be more productive, I would say go for it.
But I think this is something we wouldn't change.

**Comment by brandonroberts** [comment]
The example app is not an extension of the style guide. Its to show common and best practices.
