### ISSUE TITLE
Can't use time progression when testing effects

### ISSUE THREAD

**Issue by TKul6** [ngrx/platform#1261]
## Minimal reproduction of the bug/regression with instructions:

Just create any effect that return a delayed action (in my case 15 minutes)
When I create my tests for the effect using the time progression feature the test fail because it can read the time progression syntax (it expects a stream of 4 elements because it reads the `15m` as three different entities).

## Expected behavior:
Support the time progression feature.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

   "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^6.0.1",
    "@ngrx/store": "^6.0.1",

    "@angular/animations": "6.0.3",
    "@angular/cdk": "^6.3.0",
    "@angular/common": "6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "6.0.3",

node 9

## Other information:
According to the rxjs documentation I need to create a test schedule but since ngrx wrapps the testing framework I'm not sure how to use it. 

Thanks,

**Comment by kouMatsumoto** [comment]
It's recommended to use jasmine-marble module for testing to Effects. It's also used in the sample application of this project. 
You need not set up TestScheduler because jasmine-marble do it internally.

*Effects Testing*
https://github.com/ngrx/platform/blob/master/docs/effects/testing.md

*Sample Code*
https://github.com/ngrx/platform/blob/master/example-app/app/books/effects/book.effects.spec.ts

**Comment by TKul6** [comment]
Thanks for the super fast replay, I'll walk through the example and see if it can help my case.

Thanks a lot.
