### ISSUE TITLE
build: Automate publishing of example app/stackblitz file

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1297]
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Right now we are manually building the example app and writing to a stackblitz.html file that needs to be copied the `gh-pages` branch in order to be current. We can automate this process.

**Comment by timdeschryver** [comment]
I was playing with this in https://github.com/timdeschryver/stunning-octo-parakeet/tree/gh-pages.

I got it working but I think the stackblitz app breaks because as far as I know it doesn't support "typescript paths" - https://github.com/stackblitz/core/issues/220.

Demo: https://timdeschryver.github.io/stunning-octo-parakeet/stackblitz.html
But the gh pages are working: https://timdeschryver.github.io/stunning-octo-parakeet/example-app
