### ISSUE TITLE
Incompatible peer dependencies found

### ISSUE THREAD

**Issue by rajeev-john** [ngrx/platform#1397]
Hi,

## Minimal reproduction of the bug/regression with instructions:

 I migrated my project from Angular 7.0.3 to 7.0.4. On executing the command ng update or ng update --all=true give the following warning.

Package "@ngrx/effects" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0", would install "7.0.2")
Package "@ngrx/store" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0", would install "7.0.2")
Package "@ngrx/router-store" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0", would install "7.0.2")
Incompatible peer dependencies found. See above.

## Expected behavior:

Should update the peer dependency  accordingly for the ng update command to complete successfully.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular Cli 7.0.4
Angular Core 7.0.2
## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by k-schneider** [comment]
Along this same vein I'm a bit confused about the versioning of this project now.  I know 6.x was cut when updates were made for Angular 6.x.  I would have assumed that ngrx would be bumped to 7.x when updates were made for Angular 7.x but instead it was simply bumped to 6.1.2?

**Comment by timdeschryver** [comment]
NgRx 6.1.2 provides a bugfix for `@ngrx/router-store` to make it work with Angular 7.
The upgrade to Angular 7 will be available in NgRx 7.

**Comment by abbazabacto** [comment]
@timdeschryver If NgRx 6.1.2 provides a bugfix to make it compatible with Angular 7, is it not possible to update the peer dependencies which reflects this statement?

Now with NgRx 1.6.2 you will get the following warning when installing Angular 7 dependencies alongside:
```
@ngrx/store@6.1.2" has incorrect peer dependency "@angular/core@^6.0.0".
```

If NgRx 6.1.2 just is there for temporary support for both Angular 6 and 7, instead of a new major release, you should just allow both:
```json
{
  "peerDependencies": {
    "@angular/core": "^6.0.0 || ^7.0.0"
   }
}
```

**Comment by brandonroberts** [comment]
@abbazabacto normally, we wouldn't have done another 6.1.x release but we did because of the router-store issue. There is still some time left before we release V7 officially which will have explicit support for Angular V7 in its dependencies. Use the nightly builds if you want to use the latest builds with support for Angular V7.

**Comment by abbazabacto** [comment]
@brandonroberts Thanks for the reply. It was all about the peer dependency warning, my applications run correctly on Angular 7 with NgRx 6.1.2, will just ignore the peer dependency warning until v7 comes out. Looking forward!

**Comment by rajeev-john** [comment]
@brandonroberts when can we expect an official release ngrx/platform to support Angular 7 with out peer dependency warning. Recently I migrated my project to Angular 7.1.1 and now I am not able to update the ngrx/platform 6.1.0 -> 6.1.2 due to the same warning issues.
