### ISSUE TITLE
Event-driven actions

### ISSUE THREAD

**Issue by alaboudi** [ngrx/platform#1444]
The online guide seems to be encouraging capturing actions in more of an event-driven style by stating the following:

> Event-Driven - capture events not commands as you are separating the description of an event and the handling of that event.

Yet, it seems like the action examples are more command style like `IncrementHome`, `IncrementAway`, `Login`. Is this a bit of a contradiction? Was the guide potentially unclear or eluding to something else?

Funny enough, the strings they represent are more event focused (`Home Score`, `Away Score`)

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alaboudi** [comment]
@brandonroberts ?

**Comment by brandonroberts** [comment]
It could be clearer

**Comment by brandonroberts** [comment]
@alaboudi would you like to submit a PR with clearer action types?

**Comment by alaboudi** [comment]
Sure. I'll put a PR soon

**Comment by manklu** [comment]
IMO Event-Driven Actions versus Imperative-Actions depends on the point of view.

For the GUI, Event-Actions are perfect since they decouple interactions and state changes.

On the other side having to change and test the reducers to implement a new event sounds not nice. Here are Imperative Actions better which describes the changes and are easily reusable.

Leaving room for someone in the middle who translates an Event-Action to one or more Imperative-Actions

**Comment by brandonroberts** [comment]
Fixed via #1704
