### ISSUE TITLE
Documentation doesn't mention how to install packages

### ISSUE THREAD

**Issue by seekheart** [ngrx/platform#1454]
Currently on ngrx.io there is no mention of what to install in the `Getting Started` section or any other section and in addition no information is provided on how to setup ng schematics.

Lastly as a suggestion: In the sections following `Getting Started` I would suggest keeping the code blocks the same, i.e. having a file heading like the `Getting Started` section to help orient the reader.

## Other information:
Thank you! 😃 

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Hi, I agree with you that we need an installation section in the docs. Could you create a proposition and submit a PR?

Could you elaborate a bit more on what you mean with the second suggestion about the code blocks?

**Comment by timdeschryver** [comment]
Ah I see, thanks! The parts that are rewritten all have to the layout with the purple label. I'm not sure if it's worth it to rework the older snippets, or if it would be better to wait until the docs are written (since the setup is a bit different).

@brandonroberts was it intended to style the new code snippets the way they look now? Or would it be OK to remove the header and line numbers in the new code snippets? Or what are your thoughts about this?
Without it would look the same way as the "older" parts of the docs.

E.g.
![image](https://user-images.githubusercontent.com/28659384/49819561-12e89200-fd76-11e8-817d-70bcce4aa98a.png)

Would become:

![image](https://user-images.githubusercontent.com/28659384/49819543-06643980-fd76-11e8-8b82-5eb3e3b72111.png)

**Comment by timdeschryver** [comment]
@seekheart the documentation files for ngrx.io can be found at https://github.com/ngrx/platform/tree/master/docs. If there is something feel free to reach out.

**Comment by brandonroberts** [comment]
@timdeschryver @seekheart yes, the intended style is for those code snippets to have headers, because they are referencing files you can follow along with. The other snippets aren't currently part of a complete example app inside the docs set and are just inlined at the moment. 

You can wrap the code snippets in `<code-example></code-example>` tags and they will look the same as the others.

**Comment by seekheart** [comment]
@timdeschryver I might just be blind, but I looked in the path you specified in the docs and they don't seem to look like what is displayed in **ngrx.io**.

**Comment by seekheart** [comment]
@timdeschryver one last question: how to test locally what the site looks like?

**Comment by timdeschryver** [comment]
@seekheart The instructions are explained in https://github.com/ngrx/platform/blob/master/projects/ngrx.io/README.md.
(But be sure to navigate to the ngrx.io directory first, before running these commands)

**Comment by seekheart** [comment]
hey @timdeschryver could you take a look at PR #1469 I haven't gotten chance to completely finish up yet, also need to figure how to tie the new section in with the docs. Guessing there maybe a json or something that makes links?

**Comment by timdeschryver** [comment]
The navigation is indeed a JSON and can be found at https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/navigation.json.

@seekheart
