### ISSUE TITLE
Schematics: Support --project flag to specify apps or libs

### ISSUE THREAD

**Issue by rafa-as** [ngrx/platform#1455]
## Describe any alternatives/workarounds you're currently using

Now it's impossible to generate a feature, store, reducer, entity, action and effect  in a specific app or lib. To do this very common task we should create it in the default app and move it to the correct app.

Only container, because generates a component, supports the project flag.

## Other information:

Angular CLI accepts this flag since version 6.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by duard** [comment]
I need the same thing

**Comment by brandonroberts** [comment]
Sounds good to me. The workaround today is to change the `defaultProject` in your `angular.json` file before running the generate commands.

**Comment by rafa-as** [comment]
> Sounds good to me. The workaround today is to change the `defaultProject` in your `angular.json` file before running the generate commands.

@brandonroberts the workaround make sense but doesn't works for me with Angular/CLI 7. I had already tried before post the issue.

I will work on it this week to make the PR. Some tip to work on it?

**Comment by brandonroberts** [comment]
Thanks for working on this! Each schematic has a schema that is represented through JSON and TypeScript. I'll use the container as an example, because the other schematics will follow the same structure.

Container schema JSON:
https://github.com/ngrx/platform/blob/master/modules/schematics/src/container/schema.json

Container schema TypeScript
https://github.com/ngrx/platform/blob/master/modules/schematics/src/container/schema.ts

The `project` is defined in the JSON and TypeScript files for schema validation and for types support when imported. Schematics already use a [utility function](https://github.com/ngrx/platform/blob/master/modules/schematics/schematics-core/utility/project.ts#L15) that checks for the provided project. If the project is not provided, it uses the first one.

Once you add the `project` definition to the schema for the other schematics (action, effect, ...), it will pick up the provided project option when you run the generate command.

Here is an example test with a specified project you can reference to add tests to each schematic:
https://github.com/ngrx/platform/blob/master/modules/schematics/src/store/index.spec.ts#L88

If you need more assistance, just let us know.

**Comment by rafa-as** [comment]
@brandonroberts PR done! :)
