### ISSUE TITLE
Reloading the data

### ISSUE THREAD

**Issue by amitcdubey** [ngrx/platform#1578]
Hi am using selector for get state below is my code 

 ngOnInit(): void {
    this.test$ = this.store.select<SampledataModel[]>(fromStore.getDataDetails,);
    this.store.dispatch(new LoadData(this.loaddata));
    this.getSampleData();
  }
  getSampleData(): void {
    this.test$.subscribe(
      (res: any) => {
        this.data = res.content;
        this.Items = res.Items;
        this.dataTable.refresh();
      },
      
    );
  }
in this.test$ am getting array[object object]
can you please help me about my above code ,i subscribe the this.test$ is this the proper way to subscribe or not ,
and also when am performing CURD operation that data not getting load for display ..please let me know the solution ..how to load data when page is going to submit after CURD operation

**Comment by timdeschryver** [comment]
Support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or the [gitter channel](https://gitter.im/ngrx/platform).

Some pointers:
- on a create/update/delete you have to update the store state 
- I would encourage using the `async` pipe instead of using the `subscribe` function- @tomastrajan has written an article about it at https://blog.angularindepth.com/angular-question-rxjs-subscribe-vs-async-pipe-in-component-templates-c956c8c0c794
