### ISSUE TITLE
Schematics: Add schematics for effect creators

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1682]
Follow up to #1667  

1. Adds an `effectCreators` option to the `effect`, and `feature` schematics that uses the new effect creator function instead of decorators
2. The `effectCreators` flag will use a different set of files for scaffolding. This keeps our current structure with `files` intact.
3. Adds tests to verify the behavior of the previously mentioned schematics

**Comment by itayod** [comment]
hi @brandonroberts ,
I can start with this.

**Comment by brandonroberts** [comment]
👍🏿

**Comment by itayod** [comment]
@brandonroberts 
by "use a different set of files" you mean just the [template](https://github.com/ngrx/platform/tree/master/modules/schematics/src/effect/files/__name%40dasherize%40if-flat__) ?

**Comment by timdeschryver** [comment]
I'm not Brandon, but yes these will be different templates.

**Comment by brandonroberts** [comment]
Different set of files. I have a WIP branch here for action creators https://github.com/ngrx/platform/compare/schematics-action-creators?expand=1

**Comment by itayod** [comment]
Thanks @brandonroberts  and @timdeschryver 
I actually done about the same thing in my [wip branch](https://github.com/ngrx/platform/compare/master...itayod:feature/effect-creator-schematics?expand=1
) :)

but I think this solution might be an overkill for the effect case.
since most of the content in the effect file is not the method of creating effect, most of the template will be similar.

anyway, so I if you'r ok with the solution I will write the UT for it and upload the PR 😄

**Comment by brandonroberts** [comment]
I agree in the effects case that its reasonable to keep it in the same template
