### ISSUE TITLE
Docs: Ngrx Entity - Nested/Relational data and Normalization 

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [ngrx/platform#1707]
Since ngrx.io has opened, some issues have been closed regarding the community interest in more detailed recipes or stories, such as this one : #692.

The ngrx.io site is really nice and goes quite deep on explaining the mechanics of @ngrx.

But it does not answer or give any resource, regarding some quite frequent general questions, such as : **what would be the recommended approach on how to handle deep/relational data in regards to normalization with ngrx/entity.**

Some links to existing stuff could be a start : [Redux Normalizing State Shape](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape)

Some examples with ngrx entity would be greatly appreciated and I found a bunch of other guys asking around the same question : [Twitter with Mike Ryan](https://twitter.com/mikeryandev/status/914881822156345344?lang=fr)

**Comment by brandonroberts** [comment]
Hi @Stephane-Peyroutet, this is on our list of things to add to the docs for entity. The Redux doc you mentioned is a good reference point though

**Comment by Stephane-Peyroutet** [comment]
Hi @brandonroberts ,

Thanks for the quick reply and it's good to know this will be added to the docs.

I'm also really interested and excited with the upcoming integration of ngrx-data within the  @ngrx/platform.

I'm closing this one to keep the issues clean as this is or will be taken care of.

**Comment by Kleinhummel** [comment]
Would you perhaps supply a short example of how this is done before the recipe exists in the documentation? This issue now exists since april and a small explanation on how to solve this problem would help me a lot. At the moment I have an "Add-Action" for every entity whicht I call in a Effect.
Example of how I solve this so far:

- Dispatch Action: LoadPosts
- Effect (LoadPosts): Fetches posts from API
- Effect (LoadPostsSuccess): Normalize response and dispatch "Add-Action" for every entity (e.g. AddPosts, AddComments)
- Slice Entity Reducers: Add Posts (PostReducer) & Add Comments (CommentReducer)

Or should I just have one Action (AddPosts), which contains also the comments in the payload and the CommentReducer handles the AddPosts-Action?

Another problem I have: After normalizing the Posts, I can't use the same model interface to annotate the posts because now the comments array is not of type Comment[], but number[] or string[]. But I also don't want to create extra models just for the normalized shape. How should I annotate the comments array so that I can use it for the "not-normalized" form as well as for the normalized form?

**Comment by innovation-stack** [comment]
@brandonroberts do we have an update on this? Thank you.

**Comment by najibla** [comment]
Still nothing?

**Comment by peterhe2000** [comment]
Any updates on this?

**Comment by aenimaone** [comment]
I hope a solution will be found. this is a very important thing

**Comment by zacharylawson** [comment]
Any update on this? In Redux they [recommend using Normalizr](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#normalizing-nested-data) for nested data. What's the recommended approach in NgRx @brandonroberts?

**Comment by aenimaone** [comment]
Normalize can be used without problems. But I think we need a solution like [Redux ORM](https://github.com/redux-orm/redux-orm)

**Comment by peterhe2000** [comment]
Normilze should work without problem since it has been widely used in react. 
My confusion is with [twitter of mike ryan](https://twitter.com/mikeryandev/status/914881822156345344?lang=fr).
API -> normalizr -> ngrx/entity -> store.

I could just do API -> normalizr -> store but i lost benefits of using ngrx entity library. 
Hope there is a good example to show best practise.

**Comment by davidmarogy** [comment]
Is there any updates to this question? I couldn't find anything about using nested data with NGRX.
