### ISSUE TITLE
Docs: Add docs for reducer creators

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1762]
Follow-up to #1746  

- Document usage of `createReducers`
- Keep references to using a reducer function with a switch case for current users

**Comment by alex-okrushko** [comment]
I'll take it

**Comment by brandonroberts** [comment]
👍

**Comment by zetsnotdead** [comment]
I think it would be beneficial to mention providing the reducers for AoT.

```typescript
export function reducer(state, action) {
  return createReducer(...);
}

StoreModule.forFeature('feat', reducer)
```

**Comment by brandonroberts** [comment]
Just for clarity, we're generating the reducer outside the exported function in the schematics, but the point still remains.

```ts
const someReducer = createReducer(...);

export function reducer(state: SomeState | undefined, action: Action) {
  return someReducer(state, action);
}

StoreModule.forFeature('feat', reducer)
```

**Comment by alex-okrushko** [comment]
Putting it for myself so I don't forget all the info that's needed:
- before/after of simple reducer
- explain the need for proper typing of `initialState`
- add the note to always pass `state` into `on`-reducers (so that the return type is inferred correctly)
- explain how many actions could be provided for a single `on`-function
- explain how to wire it up for `forFeature` - including the case if it's the only reducer for the feature
- explain how to wire it up for `forRoot` (using token - if I won't have time to make it take the fn)

**Comment by fxck** [comment]
Could `on` accept different kinds of the first param? Say if I wanted to catch any action that has `entities` on it? Should I handle this outside `createReducer`? 

How about something like 

```
on(({ entities }) => !!entities), (state, action) => state)
```

**Comment by timdeschryver** [comment]
I don't think this is something we would add @fxck .

We're still reacting to **unique** actions.

**Comment by fxck** [comment]
Yeah, well since you have to do this anyway https://github.com/ngrx/platform/issues/1762#issuecomment-486658862 I can live without that. :)

**Comment by alex-okrushko** [comment]
@fxck I think that could result in more brittle logic. `type` should be the only thing that defines reducer behavior, I think.
At least that's how I see it ATM.
