### ISSUE TITLE
document createSelectorFactory

### ISSUE THREAD

**Issue by alex-okrushko** [ngrx/platform#1825]
Currently docs are missing that info:
- how `createSelectorFactory` can be used to better select arrays
- what could be used instead of `defaultMemoize`

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Is this a dup of #1217 ?

**Comment by alex-okrushko** [comment]
Interesting. I think that issue was open with the intention of adjusting the API. I think that one can be closed.

I updated this issue with what would ideally be mentioned in the docs. :)

**Comment by UserGalileo** [comment]
I'm sorry, I didn't have enough time at the time I opened that issue. I had started to put down some lines but I stopped because of 1) lack of time, 2) was still trying to figure out part of the source code, 3) I saw some commits that made me believe that module would have changed relatively fast (don't know why but it gave me the feeling to be something internal and not ready for the public yet, but It's been months :))

I wouldn't like to disappoint you all by saying that I'll do It, but I'd be happy to partecipate to this discussion :) I'll try to find my files from months ago to tell you what felt "strange" to me!

**Comment by alex-okrushko** [comment]
I think [Asif](https://twitter.com/iamAsifRahman) is looking into contributing to this part of the docs.

**Comment by daem0ndev** [comment]
Working on this!

**Comment by alex-okrushko** [comment]
We are still looking for a contributor for this part of the docs 🙂

**Comment by santoshyadavdev** [comment]
Cool, I will take it @alex-okrushko

**Comment by ZackDeRose** [comment]
Is this still looking for contributions?

**Comment by timdeschryver** [comment]
Go for it @ZackDeRose 👍
