### ISSUE TITLE
Example: App fails at runtime due to existing type check in createReducer

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/platform#1837]
## Expected behavior:

Found this issue when trying to re-enable e2e tests for the example app.

The createReducer function checks to make sure duplicate action creators aren't being used in the same `on` method in development mode. This causes the example app to fail at runtime.

```
Uncaught Error: Cannot enable prod mode after platform setup.
    at ni (core.js:6059)
    at Module.IVes (main.ts:9)
    at i (bootstrap:83)
    at Object.0 (_string-ws.js:1)
    at i (bootstrap:83)
    at t (bootstrap:45)
    at Array.r [as push] (bootstrap:32)
    at main.190ba58f5a8a435f2870.js:1
```

https://github.com/ngrx/platform/blob/master/modules/store/src/reducer_creator.ts#L188

When `isDevMode` is called, it locks up the run mode https://github.com/angular/angular/blob/909557d5f822a84821f07cc27680307cb76ca9d5/packages/core/src/util/is_dev_mode.ts

**Comment by timdeschryver** [comment]
🤦‍♂️ This is not the first time I get burned by it, and I keep forgetting it so it won't be the last time... I think we can't have this check available due to this.
The only way I see is to have this check in the reducer and not in the create function and we would need to change the `Map<string, ActionReducer<S>>` implementation.
 
Is this something we want, or should we remove the check?

**Comment by jotatoledo** [comment]
Im seeings this issue when trying to call `enableProdMode`. From all the dependecies in my project, this is the only one that makes use of `isDevMode`. Ill try to confirm this.

**Comment by MichaliEverson** [comment]
must be a gay man trying again to get a woman that isnt yours so the
production suite isnt avaible for your use
