### ISSUE TITLE
Can we dispatch actions from reusable components ?

### ISSUE THREAD

**Issue by chaouiy** [ngrx/platform#1935]
[This video ](https://www.youtube.com/watch?v=JmnsEvoy-gY) says that it is a bad practice to reuse actions. is dispatching actions from reusable components mean reusing actions ?

**Comment by wbhob** [comment]
You're supposed to bubble `@Output`s up from reusable components to smart components, who then dispatch the actions.

**Comment by chaouiy** [comment]
Sorry. I don't understund your comment. Can you be more explicit ?

**Comment by wbhob** [comment]
1. You DO reuse actions.
2. You DO NOT dispatch them from reusable (dumb) components.
3. You DO dispatch them from top-level container (smart) components.
	3a. You use top-level components to handle data, like selectors and action dispatchers.

**Comment by chaouiy** [comment]
@wbhob the speaker on[ this video](https://www.youtube.com/watch?v=JmnsEvoy-gY&t=303s) would not agree with you about "Do reuse actions" . 

another issue, What to write between brackets when resugin action from multiple sources ?

**Comment by wbhob** [comment]
That's not quite what he means. If two situations in your app have the same result, they should use the same action, because they're the same event. For example, if your app loads data on pageload, and has a refresh button, the two actions would be the same. Making two actions to do the _exact_ same thing should be avoided, but if two actions have distinct meanings/events/behaviors, they should be separated.

Any further questions should be asked on StackOverflow, as this is the issue tracker, not a support forum.

**Comment by alex-okrushko** [comment]
> Any further questions should be asked on StackOverflow, as this is the issue tracker, not a support forum.
