### ISSUE TITLE
Run reducers inside web workers?

### ISSUE THREAD

**Issue by Aaron-Sterling** [ngrx/platform#195]
## I'm submitting a...

<pre><code>

[ x ] Documentation issue or request

</code></pre>

## What is the current behavior?

No discussion I've been able to find (either officially or unofficially) about combining ngrx with web workers.
## Expected behavior:

Documentation do's and don'ts about ngrx and web workers.

## Other information:
Some of my reducers sort arrays and/or make new copies of them. This seems like a natural(?) fit for a function that could take place in a web worker. Good idea/bad idea/makes no difference to long-term execution since store.dispatch might run in the background already?

Thanks very much.

:heartpulse: ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)

**Comment by danielgek** [comment]
@Aaron-Sterling take a look at #102

**Comment by robwormald** [comment]
Theoretically, this is possible, but the cost of serializing/deserializing the state on every change (no memory shared with a worker, so you'd have to postMessage(JSON.stringify(state)) is likely to outweigh any gains. Communication with a worker is necessarily async, whereas store's API is all sync. 

It makes more sense for Effects - there's already an open issue for that.

**Comment by phenomnomnominal** [comment]
Could [SharedMemory](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) alleviate some of the performance concerns?

**Comment by sandangel** [comment]
Hi everyone, I've found this great library from creator of Preact.js: https://github.com/developit/stockroom

Is this feasible to offload entire ngrx store, effect, reducers.. to a web worker and angular can communicate with it by a service like this: [web-worker.service.ts](https://github.com/Tyler-V/angular-web-workers/blob/master/src/app/fibonacci/web-worker/web-worker.service.ts)

**Comment by brandonroberts** [comment]
See https://twitter.com/MikeRyanDev/status/954151139968249857 😉

**Comment by sandangel** [comment]
Hi @brandonroberts, I'm investigating on this topic because I have trouble with large entities ( > 10000 object ). After get data from server and put it into store, my application totally lost interaction. I plan to wrap entire ngrx/store and effects into a service which has a same API with Store. As you has point out that would make everything around 350ms slower, but it can be acceptable when you have to handle a large entities without blocking the main thread. What do you think?

**Comment by MartinFreire** [comment]
I have the same problem as @sandangel
I have an internal app for a company that uses the app on remote places with low access to internet 
So I used firebase to cache the results and try to provide a better user experience, turns out firebase doesn't handle low internet that well and the querys take way too long, so my next step was to setup a store but same problem, I have around 10k records and thought that moving that to a worker would be ideal, turns out that as it's not a common case, there is little progress with any library and my options are really limited 

Having this working would help a lot in a lot of really specific cases, I'm working on a new project for an hybrid app that handles a lot of things at the same time, intervals for alarms, printing receipts, pulling from server, handle user interactions. Something like this will really make use of a good worker to split work across threads
