### ISSUE TITLE
RFC: Component: `ngrxLet` and `embeddedView`

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2051]
## Minimal reproduction of the bug/regression with instructions:

When setting up a context variable in a structural directive we have to work with `viewContainerRef`. 
There is a `createEmbeddedView` and a `clear` method on this object. 

My question here is should we.
a) mutate the viewContext object (done atm) and clear on `ngOnDestroy` 
b) `clear` and call `createEmbeddedView` again on every change
c) don't use at all because of this => https://github.com/angular/angular/issues/15280#issuecomment-430479166

related line of code can be found [here](https://github.com/ngrx/platform/blob/4126aeeeede7a4d218fe31f0005f845630222af7/modules/component/src/let/let.directive.ts#L149)

## Expected behavior:

provide a view context object in the right and performant way

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by fxck** [comment]
Would this retain the type so the language service would pick up the properties? Is it even possible?

**Comment by SanderElias** [comment]
Because of option `c` we should not be doing `b`. 
Creating a new view every time is a very costly operation. (relatively speaking)

We only can use option `A`. If we destroy the view at all, we will break references people are counting on. The most common use-case for this is that people want to use `@viewChild`, recycling the view (option `b`) will do unexpected (to most) things then.

**Comment by BioPhoton** [comment]
The first version of the let pipe is included here:
https://github.com/ngrx/platform/pull/2046

Please check @SanderElias
