### ISSUE TITLE
Re-triggering mock selectors

### ISSUE THREAD

**Issue by timdeschryver** [ngrx/platform#2121]
## Minimal reproduction of the bug/regression with instructions:

If we override the selector's result during a test, we have to use `mockStore.setState({ random: 'data'})` (maybe we could add this into `MockStore`, @tomastrajan coined `mockStore.triggerSelectors()`?). Because of this we get a new state reference and our selectors will re-execute.

It seems like component only gets the new data if we use the `select` pipe and not the `select` method on the `store`.

```
// fails
this.todos = this.store.select(fromTodos.getAllTodos);

// succeeds
this.todos = this.store.pipe(select(fromTodos.getAllTodos));
```

```ts
it('should render todo items', done => {
    mockSelectorGetAllTodos.setResult([{ name: 'bbb', done: true }]);
    mockStore.setState({ dummy: true });

    fixture.detectChanges();
    setTimeout(() => {
      expect(getTodoItems().length).toBe(1);
      expect(getTodoItems()[0].nativeElement.textContent.trim()).toBe('bbb'); // fails here
      done();
    });
  });
```

A reproduction can be found in @tomastrajan's repo:
[Component](
https://github.com/tomastrajan/ngrx-test/blob/ab345628aee25af304e424cc326ef21db38672b8/src/app/features/todos/todos.component.spec.ts#L50) and [Test](https://github.com/tomastrajan/ngrx-test/blob/ab345628aee25af304e424cc326ef21db38672b8/src/app/features/todos/todos.component.spec.ts#L50)

## Expected behavior:

It should work in both cases.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
8.2

**Comment by tomastrajan** [comment]
Yes, this would be very nice as currently, when using override selector in component tests, I usualy override them in every test instead of in before each and then just using `setResult()` because as tim described that would not work.

The idea was that as `fixture` has `detectChanges()` the mock store could also provide standardized well-known method to push new values to mocked selector.

The best would be if that happened automatically just by using the `setResult` but if thats not possible because of technical reasons, standardized method would be good too!

**Comment by brandonroberts** [comment]
A `MockStore.refreshState()` seems reasonable to me. Wouldn't we just be able to store the current state and spread it into a new object internally to set a new reference?

**Comment by timdeschryver** [comment]
Sounds good!
