### ISSUE TITLE
store.select not working => argument of type 'mystate' is not assignable to parameter of type.

### ISSUE THREAD

**Issue by smatthews1999** [ngrx/platform#214]
Having this issue every time I try to 'select' state instead of subscribe.

![capture2](https://user-images.githubusercontent.com/562964/28745074-09e3ceee-743e-11e7-95ad-366dc4806de7.PNG)
![capture](https://user-images.githubusercontent.com/562964/28745075-0d30f4dc-743e-11e7-8f29-c028c46ea5ea.PNG)
This is a simple example and I have followed setup of store and reducer closely...
On the other hand 'subscribing' works as expected...
![image](https://user-images.githubusercontent.com/562964/28745097-be06a9e6-743e-11e7-81fa-4b5496a02dae.png)

"@ngrx/store": "^4.0.0",

**Comment by antonyRoberts** [comment]
@smatthews1999 Need to see how you're importing and exporting your reducers, because from what you've given there's not enough info other than to say you should not be getting store.select like that. In your case it should be 
`this.store.select(AppState.canvas)`
but that would mean you are importing your reducers along these lines
`import * as AppState from yourReducerFile` and exporting just the state of the canvas from that file.

Also it looks like you're going to want canvas data async, so you may want to make use of Smart/Dumb style with containers and components and pipe the data in async from the smart component to the dumb ones.

Look at this setup in the example app for an idea of how things should flow
 1) [Reducer Index](https://github.com/ngrx/platform/blob/master/example-app/app/books/reducers/index.ts)
2) [Smart Container](https://github.com/ngrx/platform/blob/master/example-app/app/books/containers/find-book-page.ts)
3) [Dumb Component](https://github.com/ngrx/platform/blob/master/example-app/app/books/components/book-search.ts)

Any chance the example you're talking about is the counter example?

**Comment by smatthews1999** [comment]
Thanks for your response.  
My usage of ngrx/store has thus far been a simple scenario of a single reducer, state object and actions.  I have no need to go beyond that right now.  
app.module
```
import { StoreModule } from '@ngrx/store';
...
 imports: [
    BrowserModule,
    FormsModule,
    StoreModule.forRoot({ state: CanvasReducer }),
  ],
```
reducer
```
import { Action } from '@ngrx/store';
import { Store } from '@ngrx/store'

export function CanvasReducer(state: AppState = initialState, action: Action):AppState {
  let newState = Object.assign({}, state);
  switch (action.type) {
    case SET_CANVAS_WIDTH: {
      newState.canvasWidth = (<SetCanvasWidthAction>action).width;
      return newState;
    }
    default: {
      return state; // unmodified
    }
  }
```
actions
```
import { Store } from '@ngrx/store'
import { AppState } from './reducer.service'

export class SetCanvasWidthAction implements Action {
  readonly type = SET_CANVAS_WIDTH;
  constructor(public width: number) { }
}
setCanvasWidth(width: number) {
    this.store.dispatch(new SetCanvasWidthAction(width));
  }
```
my component and subscribe to store
```
 constructor(private store: Store<any>) {

    store.subscribe((state) => {
      let s = state;
      this.appState = <AppState>s.state;
    });
```
This is what I am doing to get a typed AppState object (which is a bit more convoluted than 2.x).

**Comment by brandonroberts** [comment]
What does your `AppState` interface look like?

**Comment by MikeRyanDev** [comment]
your problem is this line:

```ts
this.canvasState = this.store.select<AppState>('canvas');
```

You need to remove the generic type parameter from `select` and instead just do this:
```ts
this.canvasState = this.store.select('canvas');
```

The types should flow correctly since you've specified the generic type of `Store`.

[See the type signature here](https://github.com/ngrx/platform/blob/master/modules/store/src/store.ts#L26)

**Comment by smatthews1999** [comment]
@brandonroberts 
```
export interface AppState {
  canvasWidth: number
}
```

**Comment by smatthews1999** [comment]
@MikeRyanDev 
There is no way for me to create the Store without the type, and subsequently no way to refer to it w/o the type
![image](https://user-images.githubusercontent.com/562964/28822900-209c4c86-7689-11e7-88b8-2c8684ab6f98.png)

**Comment by littleStudent** [comment]
```Javascript
constructor(private action: ActionService, private store: Store<AppState>) {
  this.appState = this.store.select('state');
}
```

probably take a look at the [example](https://github.com/ngrx/platform/blob/master/example-app/app/books/containers/find-book-page.ts).

**Comment by smatthews1999** [comment]
@littleStudent 
I did look at the example on the main page...
```
export class MyAppComponent {
	counter: Observable<number>;

	constructor(private store: Store<AppState>) {
		this.counter = store.select<number>('counter');
	}
}
```
I am quite sure that it does not compile.

**Comment by RemotecUK** [comment]
This had me stumped for quite some time.  What is wrong with the OPs code if the `canvaswidth` property is a number? Why does the typing to the `number` type not work when getting it from the store in this case?
Thanks.

**Comment by houmanka** [comment]
@smatthews1999 Have you found a solution for this?

**Comment by smatthews1999** [comment]
I am afraid not.  I rolled back to 2.x.  I asked this question several times and I kept getting answers like "your solution is not complicated enough... you need to use more cool features".   I honestly don't get how they can put the code in the readme and it not work.  I also don't understand how a defined typed object (the state) cannot be delivered as such (a typed object).

**Comment by DeanHristov** [comment]
@smatthews1999 I have the same problem I fill a bit uncomfortable. Usually, in React this case can be solved a really easy. I can not understand why in AngularJS the most of things are so hard?

**Comment by brandonroberts** [comment]
@DeanHristov I'm not sure what issue you are having. Please provide an example so we can point you in the right direction.

**Comment by smatthews1999** [comment]
@houmanka My solution has been to use [Mobx](https://github.com/mobxjs/mobx-angular)... sorry.

**Comment by EthanSK** [comment]
this is still an issue. please type 'select' properly
