### ISSUE TITLE
RFC: Accept InjectionToken in EffectsModule.forFeature

### ISSUE THREAD

**Issue by leon-marzahn** [ngrx/platform#2232]
It is currently not possible to register effects (`EffectsModule.forFeature`) with an `InjectionToken` like it's possible in `StoreModule.forFeature`. Adding this feature could open some possiblities of reducing boilerplate in applications.
Pull Request #2231 (Help needed for how to document and test)

## Describe any alternatives/workarounds you're currently using

An alternative is using `InjectionTokens` for everything but the effects, but that leads to some complications, an example from my current project:
```
EffectsModule.forFeature([
  FeatureStore.createEffects(
    ACTIONS_TOKEN,
    FeatureService,
  ),
])
```

## Other information:

Hey there, this is my first attempt at contributing and this is my first feature request :D

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
What's your use case? Reducing boilerplate is not a use case 😉

**Comment by PsychoPflanze** [comment]
@brandonroberts My specific use case is to reduce boilerplate. I want to create a library that makes it possible to create actions, reducers, effects and selectors via a single class. And because this already works in `StoreModule.forFeature`, it would make sense to also have it in `EffectsModule.forFeature`
