### ISSUE TITLE
Docs: does state in @ngrx/entity require manual deep copy? 

### ISSUE THREAD

**Issue by anno1985** [ngrx/platform#2312]
The docs for @ngrx/store point out that the spread operator only makes shallow copies of objects and direct users to look into using deep copy libraries. 

My understanding is that they only make sense if state contains nested objects or collections of objects. 

From what I've read, deep copies seem to be required only for time travel functionality. Change detection is done via shallow comparison of the state or its slices (ie. root objects), not by comparing each object in the state. 

@ngrx/entity however doesn't specify if deep copies would be required if the entities it manages are nested objects (instead of flat ones). I've tried to go through the code on my mobile, and have only seen the spread operator being used, which would indicate deep copies should probably still be made when modifying entities, but I probably missed some finer details. 

Can you please confirm if my assumptions are correct, and especially if deep copying (e.g. using immer.js) is advisable when using @ngrx/entity (or if it's taken care of/unnecessary)? 

Happy to draft a few sentences for the docs and submit a PR. 

## I would be willing to submit a PR for the docs :heart:

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by RobertAKARobin** [comment]
I would like to know this too.

**Comment by dungtm007** [comment]
Practically, I think:

1. At the time of reducer:
- We deal primarily with the state object at its root / first level properties.
- Any possible modification will be re-setting a first level property with new value come from action.payload. This is our intention and the new value (even primitive or object) we know the expected value. 
- For other state's first level properties that we don't tend to change, if the shallow copy of state still refers to their original references, that would be fine. Because:

2. Redux framework to make sure actions/effects to be handled and pass sequentially to reducer. 
- At one time, the state should be only examined and modified by one reducer code for a specific action
- Also, other places other than reducer (e.g. effects), state object should not be touched directly

Just my thought. 
Theoretically regarding the deep copy per NgRx requirement, I'm also curious if it should be strict or not.

**Comment by brandonroberts** [comment]
NgRx Store does not provide a copy to reducer functions, which means you must do a deep clone if your object has deeply nested properties.
