### ISSUE TITLE
No type-safety for selector's projector function

### ISSUE THREAD

**Issue by dzonatan** [ngrx/platform#2317]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/5166666/72372715-83977600-370f-11ea-9d66-c3c00e51ddf6.png">

Is there a reason why projector function does not have a type-safety for its parameters yet?
This quickly becomes a nightmare when having a lot of unit tests for complicated projectors.
I've looked into internals and found that for some reason the [`MemoizedSelector`](https://github.com/ngrx/platform/blob/2cc88857421b74e01b816f99fe28234bbe77ff1f/modules/store/src/selector.ts#L34) is using a default type [`DefaultProjectorFn`](https://github.com/ngrx/platform/blob/2cc88857421b74e01b816f99fe28234bbe77ff1f/modules/store/src/selector.ts#L17) for its projector which does not know anything about parameter types but only `Result`:

```ts
export function createSelector<State, S1, Result>(
  s1: Selector<State, S1>,
  projector: (s1: S1) => Result
): MemoizedSelector<State, Result>; // <-- third type is a `DefaultProjectorFn`
```

This could be easily fixed by explicitly providing a type of projector function (for every `createSelector` of course):
```ts
export function createSelector<State, S1, Result>(
  s1: Selector<State, S1>,
  projector: (s1: S1) => Result
): MemoizedSelector<State, Result, (s1: S1) => Result>;
```

<img width="692" alt="image" src="https://user-images.githubusercontent.com/5166666/72373608-4af89c00-3711-11ea-8e58-df1fcfcd5188.png">

Maybe this was already discussed? Are there any hidden issues that I'm not aware of? 
Otherwise it's strange why this was not escalated yet.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes
[ ] No

I have all the changes ready to be reviewed - just let me know if the solution here is appropriate.

**Comment by timdeschryver** [comment]
The change looks good to me!

**Comment by alex-okrushko** [comment]
So even the usage of `DefaultProjectorFn` I had to revert within Google's repo to `AnyFn`, because  some of the quirks of the TS. For example, in TS accessing Array by Index always gives you the result with the type and never `undefined`, which is clearly not what it should be (microsoft/TypeScript#13778)

I tried to demonstrate [the problem here](https://www.typescriptlang.org/play/index.html#code/PTAEFpK6dv4YgUCUheDcOI7oC2BLAdrtgIYA2oAcgOYBKAHqAM4CmpzAxgC4D2ATqEQAObbM3ydinXN3xJmdQX06hOAT0HNQAZVYcevADwAVADSgAagD5QAXlAAKRhM7MAXKCMBKW9fMBuOQUlFXVNABFmADNiAFdSTgAFXm4AKz0+ADF8Y2s7ewA6QuJeKkZ3YnxVAG0AXW8bayMAwMVeZQIXXmj2TQBZZmxuXAAvZgATHTYuPgMkUG1nZhM50BpmRjjOZfmk1PTeLNtQCOjN3bTpg+y1jfjLJGt5F3wxxm1dS4MtRbMbzesAN4rXi6YgseyedwANyGYwC80EyQu+ncBSKJTKoAq1TqPlW6028KYzE4f3iqJBt04AH53GTOPVrDDcHCVuw2MV6ajGaBmayAL5IFrBSIxfBcaT4UDsEGSZiTfZfH7aACMvwJd3sK3mjBV7gVn2+crMWhVlm281AiL2l1Ruv1Kp59KQkNA-UGI3GBv0SuN+KpgNA2ulMic0rIpGIACM2EdHPrFjzrci+I4VY5PJ4ifMQZwYrwpQB5KPI-Jgxi4Kj4ezsCPRthmIGW5tWpH7C0t0Agjksbl4gGgfkdlssUkazgU8e0-2bHkDofB5vs5ic8d9hqgefD-lZpCC1BoQBiOzgCEQyJRaAwWFN9AJsMIBmJnJKUGBEO+P5+EEKOswusQelAYsUk3INmxZdwnF4AgqACfcwB4QRQDYKFWGJG8+FASJMM4AALTQAEFeF4YhVFAbhIiAgAhAApABRABhIwtCQdhQ2Ua89CIkiyLyV1gNqPEqgHCDQAAcmIMTB0bAQxncMSoykodQNEsT2CUmpmlY9isS4GIyG9TC7BlFcXEM3gtWbTiuG40jh1QTtLUwUB8G4KRALwyRQAAd00ACekYN48M0AgxnkFRcK87zuDiMYuxJfMpTFMLIgIcZg2KfgN0yqoVQABjympQAAH2Kly4lIYNUAACW4XzUP4AgPC0XSAorfAqCxYjSNAKMyNC8LvNwUhyDIbzSLeKhcFQ0BVBiiLNEpTYqrAIa8K6niQg0LEXhc5gGvE5KojSsYxLMRhuGaiKCAAazeAADUrypG+6fOG8h8H2v9QEiwQNFkTwhQcpysGCgR8EiP8QTitRttwN5gJ2uLXOUYDivwCrtPwMMlviI4ALzAyPn0fJk32exhNk+TJMHOpmlQAipTw+G3pG3rNDB60YwGcHQBosE8E+lR1k4N4kDC9lik0UVxSkGRQHkDQuByewJw8V17AHHg6IAR300gKXcLw8SjbhuA5KUd3psBHNtxz8JBBbW24bnsAEN5cMrXDSC9lw4swFo9HsAn9fM0m20uCmRLk8Saf5OpPHybW9bIewMZG3dUDo4i+HcIiqBiURxHIyjYc0MT09IKSWZRrFAsrfB6w5y7BGKYhRE6EutvL4CxKFIA)

Of course, there is a solution - to give the explicit return type to the projection function, and maybe that's the right solution, but it's hard when this change is introduce later into a huge codebase.

What I what to highlight here is that `.projection(...)` is used in tests only and if you pass something that is mistyped into it - you'll most likely get an error. Yes, it'll be a runtime error of the failing test and not compile time error, but "fixing" it might create more problems upgrading to a newer version of NgRx. Is it worth it? I'm not sure.

**Comment by dzonatan** [comment]
I hear you and agree that this is kinda a breaking-change. Even the example-app tests in this repo has a few usages of projector func that would break. But by not having type-safety here we're losing other perks like language-service support - rename and other stuff.. now when refactoring you have to do it in old way with find & replace. As you said - most of the time this will result in a runtime error, but not every - so because of these few times you still have to go through all your usages and fix it manually, otherwise your codebase soon will lose integrity.

Also `projector` function is not technically limited to tests only. I've seen some cases when it was used in the implementation, although I'm not convinced it is a good practice.

**Comment by dev054** [comment]
Hey, any chance to revisit it before v11? It's a pain to use projector without type-safety.

**Comment by NicBright** [comment]
I've run into the same typings problem and wished the `.projector` was properly typed.

Quoting @alex-okrushko 
> What I what to highlight here is that .projection(...) is used in tests only and if you pass something that is mistyped into it - you'll most likely get an error. Yes, it'll be a runtime error of the failing test and not compile time error, but "fixing" it might create more problems upgrading to a newer version of NgRx. Is it worth it? I'm not sure.

Yes, fixing this issue is definitely worth it, because NgRx itself is a project written in TS. For my part, this makes me expect that types should be handled properly, even in tests.

Regarding the breaking change dilemma. When you don't want to break existing functions, there's a classic solution: provide the fixed version under a new name, deprecate the old name, wait for a given period and then remove the old version.

You can even do it the other way round (with a little bit of extra effort): rename the current version to maybe `createSelectorDeprecated` (and provide the fixed version under the current name `createSelector`). Additionally, provide a script  that automatically updates all imports with an alias (I'm thinking of an update helper similar to `ng update`).

Previously: `import { createSelector } from '@ngrx/store'`
With alias: `import { createSelectorDeprecated as createSelector } from '@ngrx/store'`

**Comment by david-shortman** [comment]
What about introducing a new test method instead that is type safe @alex-okrushko?

proposed tiny change: https://github.com/david-shortman/platform/commit/e7065b182c243cd365428df85e8f758ee048ab52

By introducing a (hopefully someone could come up with a better named) function like `testProjector`, we could be able to do the following without any need to break and migrate existing code:

```typescript
const selectSomeSum = createSelector(a => a, b => b, (a, b) => a + b);
const result = testProjector(selectSomeSum, 1, 2); // 3
```
