### ISSUE TITLE
Over-optimized, over-blown

### ISSUE THREAD

**Issue by cherryland** [ngrx/platform#2355]
I use the example-app from time to time to remind myself how ngrx works. Because I do all kind of other things besides working with Angular. And I am with ngrx since the day one. Now this is a perfect opportunity for you to gather insights from developers and measure the developer experience.

The example-app has become a mess and is totally overblown and over-optimized.

In fact, you can clearly see that some people have nothing better to do than to push **pseudo-optimizations**. I guess it's for the bare sake of **recognition**. Boss look, I pushed something to a celeb repo. Wow, truly impressive. Good boy.

To bring it to the point: The simplicity is gone. And it sucks.

I am hereby asking the maintainers to stop giving in. Just say no to those idiots. Learn to reject pull requests.

@brandonroberts 
@MikeRyanDev

**Comment by AlexAegis** [comment]
I just checked it and it even has an ellipsisPipe. Why would anyone write something like that when the css solution works better. We rarely use monospaced fonts on the web, relying on string length is inconsistent.

I'd make a simpler example app and rename this to something else (I still wouldn't throw it away completely)

**Comment by brandonroberts** [comment]
@cherryland @AlexAegis 

Thank you for being with NgRx since our early days, the team is really appreciating that you remained with us through all our changes, and improvements.

We are sorry that you **feel** that the example-app is no longer up to your standards, and we are open to your suggestions on how we can improve it. 

We are always looking for ways to make the example-app better for those who are new and experienced users of NgRx and one of the purposes of the example-app is to show how some of the techniques could be applied on a way more complicated app, and indeed might not be needed for the example-app-level complexity app. We are trying to balance that.

Another thing to note is that the NgRx project itself is supported and maintained by the community, and volunteers who are trying their best to keep it going. Calling our contributors “idiots” does not bring any value to the table, instead we prefer to hear some constructive arguments, suggestions, and pull requests, if you have any.

Thank you, NgRx team.

**Comment by alex-okrushko** [comment]
I'll close this for now. Some further possible actions are outlined above 👆
