### ISSUE TITLE
Ngrx not compatible with angular v9

### ISSUE THREAD

**Issue by Brian611** [ngrx/platform#2424]
Error on ng add @ngrx/store : 

"The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support."

Updating ngrx/store with ng update @ngrx/store :

"Package "@ngrx/store" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0", would install "9.0.2")"

**Comment by brandonroberts** [comment]
For others trying to use Angular v9 with NgRx v8, use the `@latest` tag when using `ng add` to get the latest released version according to npm. The Angular CLI tries to figure out the version to install, taking into account the peer dependencies. This is why NgRx 1.2.1 is being chosen without using the `@latest` tag. This issue is not present if you are installing NgRx v9 after it goes final.

```
ng add @ngrx/store@latest
```
