### ISSUE TITLE
ngrx 9 is collapsing when trying to put some big object reference to store (NgbModalRef or ActivatedRouteSnapshot)

### ISSUE THREAD

**Issue by DzmVasileusky** [ngrx/platform#2578]
After migration to Angular 9, I updated ngrx from 8 to 9.
It cause some issues for existing store logic.
We used to store ActivatedRouteSnapshots and ng bootstrap (NgbModalRef) modals there.
But now it cause errors.
For NgbModalRef it:
`ERROR TypeError: Cannot freeze`
`ERROR Error: Cannot assign to read only property 'state' of object '[object Object]'`
`Error: Cannot assign to read only property 'taskData' of object '[object Object]'`
`Attempting to configure '__source' with descriptor ...`

See the sandbox below for details

## Minimal reproduction of the bug/regression with instructions:
https://stackblitz.com/edit/ngrx-seed-tjytfh?file=src%2Fapp%2Fapp.component.ts

## Expected behavior:
NgRx should be able to store any objects. Especially ones like componentRefs, routeSnapshots etc.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
@angular/core9.1.11
@ngrx/store9.2.0
rxjs6.5.2

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by brandonroberts** [comment]
This is intended behavior with the runtime checks being enabled by default. https://ngrx.io/guide/store/configuration/runtime-checks. The store works under the assumption that you're storing plain JavaScript objects, and not complex objects with references. You can disable the checks if you want to pass those types around, or use a service instead of passing it through the store.
