### ISSUE TITLE
I upgraded angular v9 to v10 but the ngrx dependencies are not supported 

### ISSUE THREAD

**Issue by maniya108** [ngrx/platform#2592]

**Comment by brandonroberts** [comment]
The NgRx 9 dependencies are compatible with v10, just with the included peer dependency warning. We will start our release cycle soon for NgRx v10, and publish a beta against Angular v10 packages

**Comment by yusijs** [comment]
@brandonroberts this might be a coincidence, but we're having a lot of issues with ngrx after upgrading to Angular 10. We don't get these errors in dev, only in prod-builds, but they're always referring to some or another ngrx dependency:
- 'Cannot read property selectors of null'
- Injector errors pointing to Effects (`NullInjectorError: R3InjectorError(t)[t -> InjectionToken ngrx/effects: Root Effects -> t -> t -> w -> w -> w]:`)

Again, this only happens in prod-builds, and never during local development.

**Comment by timdeschryver** [comment]
@yusijs if you can create a reproduction it will be easier for us to take a look.
Have you tried to use NgRx 10.0.0-beta.0?

**Comment by yusijs** [comment]
Havent tried the beta, no. Like I mentioned, it only happens for production builds, and it seems very random - if I run the same build-job in our pipeline again, it works without a problem. I'm not convinced this is purely ngrx' fault, but I'm not able to give you a good reproduction since it happens randomly, in a *huge* application. I just wanted to chime in with the fact that there may indeed be a problem, and give some errors. The rest of the information is that it happens in main.<hash>.js on line 1, column 577951 which is super-unhelpful :D
