### ISSUE TITLE
Ionic Redux remote device debugging.

### ISSUE THREAD

**Issue by jcfernandezgithub** [ngrx/platform#2724]
Hi I'm Chris,
I'm struggling to debug using redux on ionic framework via remote device. Redux Devtools says "Store not found".
There some documentations available to integrate that feature?

**Comment by timdeschryver** [comment]
Hi, support questions should be asked on [stackoverflow (with a ngrx tag)](https://stackoverflow.com/questions/tagged/ngrx) or you can join our [discord server](https://discord.com/invite/gCEj4zC) and ask your question there.

**Comment by kawazoe** [comment]
the lack of documentation around this feature is staggering. Everything I find explain how to setup your own messaging server instead of using remotedev.io for the remote-redux-devtools extensions but even then, there is zero information on how to connect the ngrx devtools to it.

I think this issue should remain open as a request for better documentation.
