### ISSUE TITLE
forFeature() state defined in lazy loaded component is not visible in main state tree

### ISSUE THREAD

**Issue by tscislo** [ngrx/platform#2797]
I'm using Angular 9 **component lazy load feature**. Basically I'm using this pattern: https://brianflove.com/2019-12-13/lazy-load-angular-v9-components/
Here is my component, with NgModule definition as well as some ngrx imports

```ts
export class DetailsLazyComponent implements OnInit {
  constructor(
  ) {
  }

}
const ngrx = [
  StoreModule.forFeature("LAZY_FEATURE_STATE", {
    comments: commentsReducer
  }),
  EffectsModule.forFeature([
  ]),
];

@NgModule({
  imports: [
    ...ngrx,
  ],
  declarations: [
  ]
})
export class CostOptimizationDetailsModule {
}
```
I import this component somewhere else using
```ts
import('../details-lazy.component')
```

## Expected behavior:

I'd like LAZY_FEATURE_STATE to be present in my state tree. However it is not there.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

ngrx version 10.0.1
Angular 9.1

**Comment by markostanimirovic** [comment]
@tscislo can you provide a github repo or stackblitz live example where this issue is reproducible?

**Comment by brandonroberts** [comment]
@tscislo lazy loading a component/module in this way does not compile the module, which is why lazy loading doesn't register the state. This is something that would need to be supported upstream by the compiler. 

Does the constructor of the NgModule run? If so, you could work around this by injecting the ReducerManager and adding the state manually. Same with the Effects.

**Comment by timdeschryver** [comment]
Feel free to join the [NgRx Discord Server](https://discord.gg/ngrx) for further help.

**Comment by tscislo** [comment]
@brandonroberts unfortunately constructor of such lazy loaded module doesn't run, therefore I don't think such use case is currently supported by ngrx.

**Comment by alxhub** [comment]
I think the problem is independent. When lazy loading is performed via the router, for example, a rather complicated sequence takes place:

1. An `NgModule` is lazy loaded, and used to create an injector (which instantiates the NgModule class)
2. From that injector, the `ROUTES` token is injected, which retrieves the route configuration that was loaded
3. The route configuration points to a component which can then be requested via the module's `ComponentFactoryResolver`.
4. Finally, a component is instantiated (with the NgModule's injector as its parent injector).

Lazy loading via `import('../details-lazy.component')` is a very different operation, which directly loads the compiled component class only. The component's NgModule is not loaded (unless its incidentally loaded in the same file) and no injector is created from the NgModule.

Nothing in Angular requires that a lazily loaded component be created using an injector from its own NgModule. Lazy loading in the router works this way, but otherwise it does not happen automatically. You'd have to explicitly code for this behavior if you rely on it.

**Comment by tscislo** [comment]
@alxhub thanks for you explanation.
In this case however my component file contains NgModule (LazyDetailsModule) which is required, because it contains some imports (other NgModules) for lazy loaded component to run. Without those imported NgModules (in LazyDetailsModule) my lazy loaded component does not work.
Therefore I think my LazyDetailsModule is "processed" somehow via Angular Compiler, but probably not in the way you described above. Is that correct?

**Comment by alxhub** [comment]
@tscislo this is by far the most confusing thing about NgModules - they do two, completely independent jobs.

1) They determine the context for a template. If you write `<foo-cmp>` in a template, the NgModule determines which component will be used there. This is evaluated when the component and NgModule are compiled together in the same program.

2) They specify providers which will be used to build an injector. If you ask the injector for the token `Foo`, the NgModule(s) used to build that injector will be searched for provider(s) for `Foo`.

When you dynamically instantiate a component, via `ViewContainerRef` for example, you specify which injector to use for DI when doing so (the 3rd argument to https://angular.io/api/core/ViewContainerRef#createComponent). If this isn't specified, the injector of the `ViewContainerRef` - that of its host component - will be used by default.

Your lazily loaded component requires a certain configuration to be present in its injector, and it _so happens_ that the component's own NgModule sets up providers for this configuration. In order for the component to work when it's dynamically created, the injector used has to be created out of that NgModule, so that it'll have the right providers. Nothing in Angular _requires_ that injector to be used, nor does it happen automatically.

So lazily loading the component is only half the picture. To make your component work, you would also need to load the NgModule, create an injector from it, and then use that injector with `ViewContainerRef.createComponent` when instantiating the component.

In other words, this pattern of having the component's NgModule configure providers for the component is only a convention, and it requires explicit glue to create the right injector from the NgModule when instantiating the component.

This was never really a problem before, because lazy loading done via the router has always loaded full NgModules, not components. The router loads an NgModule, creates an injector for it, uses that injector to get the route configuration, and then selects a component from the route config and creates it _with that injector_. So routed components are always instantiated with an injector that includes providers from their NgModule, and these kinds of dependencies just work. When you lazy load a component yourself (which only became possible with Ivy), you're responsible for getting the injector right too.

**Comment by alxhub** [comment]
Yep, that looks correct to me, and should create the component with the right injector context :)
