### ISSUE TITLE
Feature request: Typesafety when using custom memoization

### ISSUE THREAD

**Issue by wiegell** [ngrx/platform#3018]
Please see this SB: https://stackblitz.com/edit/ngrx-seed-tkjpfx?file=src/app/reducers/index.ts
In particular /reducers/index.ts

When a custom memo is applied, there is no type inferred in the projector-function. A usual selector will know the type from the prev. (state)selector. Can this be solved somehow?

![image](https://user-images.githubusercontent.com/29224981/118036477-e8e39180-b36c-11eb-93cb-e52508b75a97.png)

## Describe any alternatives/workarounds you're currently using
Usually the type can just be defined manually, but would be nice not to have to do that.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Hi, the selectors from `createSelectors` are typed because we added the types [here](https://github.com/ngrx/platform/blob/master/modules/store/src/selector.ts#L125).
I'm afraid that if you want to have type-safe selectors with a custom memoization, that you'll also have to provide those.
Maybe with variadic tuple types, we will be able to support this though.
