### ISSUE TITLE
Support for rxjs 7

### ISSUE THREAD

**Issue by qortex** [ngrx/platform#3059]
When trying to update to rxjs 7, I run into:

```
Package "@ngrx/store-devtools" has an incompatible peer dependency to "rxjs" (requires "^6.5.3", would install "7.1.0").
```

Is store-devtools compatible as-is with rxjs 7, or is there some work to ensure compatibility?

That would be great.

## If accepted, I would be willing to submit a PR for this feature

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by qortex** [comment]
Sorry, it's actually much more deep: https://github.com/ngrx/platform/issues/3059

**Comment by kylecordes** [comment]
@qortex Can you explain any further about the depth of RxJS 7 issues? In the comment above you link back to this same issue.

**Comment by qortex** [comment]
Woops sorry, bad copy/paste. Here is the link I was referring to: https://github.com/angular/angular/issues/41897#issuecomment-848018116

**Comment by Legiew** [comment]
The last angular version 12.2 supports both rxjs 6.x and 7.x so maybe we can open this issue again?

My question would also be what can we do to also make ngrx compatible to both versions?

We have a NX workspace with both angular and nest and we can't update to latest nest version (which is 8) because it requires rxjs 7.x.

**Comment by dobromyslov** [comment]
@Legiew totally agree. We use NX + Nest + Angular too and experiencing same issues. Angular 12.2 builds and runs fine but I can't say same thing about NgRx. It would be nice if RxJs gets RxJS 7+ support.
