### ISSUE TITLE
Guard for forgetting to include { dispatch: false } in createEffect

### ISSUE THREAD

**Issue by inorganik** [ngrx/platform#3159]
Currently, when writing effects, If your effect doesn't emit an action, and you forget to pass the second argument with `{ dispatch: false }`, the consequences are bad. 

For instance, you might have:
```ts
actionSuccess = createEffect(
    () =>
      this.actions$.pipe(
        ofType(
          MyActions.createProductSuccess,
          MyActions.updateProductSuccess,
          MyActions.deleteProductSuccess,
        ),
        this.utilService.filterActionMessagesFor('message'),
        tap((action) =>
          this.messagingService.success(action.message, action.type)
        )
      ),
    // { dispatch: false } <-- oh no, don't leave this out!
  );
```

I've done this by accident several times and here's what happens:
- the app freezes 🥶
- no console errors/output 😶
- memory ramps up RAPIDLY to 3-4 GB, and within 30 seconds the tab crashes. 💀

This makes it very hard to debug. 

## Solution

I would like to suggest we build in a guard, that will at least throw an error at runtime indicating an effect is not dispatching and we didn't properly handle that by adding `{ dispatch: false }`.  This will provide valuable clues to the dev to help them fix it.

## Other information:
```
"@ngrx/effects": "^12.2.0",
```
## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Thanks @inorganik. We've discussed this many times before and there isn't a good way to do this without accidentally impacting valid use cases. We recommend using the ESLint rules to guard against this behavior.

https://github.com/timdeschryver/eslint-plugin-ngrx/tree/main/docs%2Frules%2Favoid-cyclic-effects.md

We add the ESLint rules to new projects when using `ng add @ngrx/store`. We could add more hints to the docs about the behavior and also about the ESLint rules.

**Comment by danielkleebinder** [comment]
I also ran into the same issue a couple of times. Especially while learning about `ngrx` and developing my first applications using this platform. A lot of modern programming languages (like Kotlin for example) set a hard limit to the call stack depth to limit the amount of recursion possible. The reason behind this is, that a call stack growing rapidly in size certainly indicates some error (even though there are a lot of valid use cases where such a scenario might occur). I am talking about this behaviour in programming languages, because I think this is a quite similar scenario here.

The [`RootStoreConfig`](https://ngrx.io/api/store/RootStoreConfig) already allows developers to opt-in to certain runtime checks. Would it be viable to add an additional flag that enables such max effect call depth warnings (don't have to be errors in my opinion)? Developers that do have use cases were (practically endless) effect dispatching is occuring simply never activate this option in the first place (or configure the max allowed depth in a way that it fits their use case). This would allow for easy backwards compatibility and would really help new developers getting used to `ngrx`. We could even elevate this approach and make it an opt-in option per feature module aswell. Meaning, that feature store modules that do take advantage of endless effect calls never activate this check and developers are always in full charge.

By adding this option, developers could easily opt-in during development or testing and opt-out during production. An example for such a config (and how the parameter might look like) is just below:

```typescript
StoreModule.forRoot(reducers, {
  runtimeChecks: {
    strictEffectDispatching: true
  }
})
```

**Comment by inorganik** [comment]
Thanks @brandonroberts. Are you saying there is a valid use case where you do not emit an action in your effect and you do not include `{dispatch: false}`, and this does not cause the issue I described?

**Comment by timdeschryver** [comment]
Closing this issue because we have added docs for the ESLint plugin.

Also fwiw, you can unit test that dispatch is set to false.

```
import { getEffectsMetadata } from @ngrx/effects;

expect(getEffectsMetadata(effectInstance).effectProperty$.dispatch).toBe(false);
```
```
