### ISSUE TITLE
`getWithQuery` method should set `loaded` property to true

### ISSUE THREAD

**Issue by Evexis** [ngrx/platform#3165]
I want to fetch the data in route resolver, using `getWithQuery` method, but it does not set `loaded` property to true. query-many/success action set only loading to false.

## getAll action - set both loading and loaded roperties
![getAll action](https://user-images.githubusercontent.com/26208171/135856256-808fbf04-2bee-4d43-abfc-fe5bfe44663e.PNG)

## getWithQuery action - set only loading, loaded remains false
![getWithQuery action](https://user-images.githubusercontent.com/26208171/135856470-539afa60-c772-4daf-9cda-6d53397ef769.PNG)

## Code I use as workaround
Calling `setLoaded(true)` after request.

![code](https://user-images.githubusercontent.com/26208171/135856532-b9fed324-8f83-40ca-805c-cfb1c764c3a5.PNG)

## Expected behavior:
getWithQuery should set loaded flag to true as well.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
ngrx 12.4.0

**Comment by brandonroberts** [comment]
If this is breaking and we want to get this into v13, now's the time.

**Comment by Evexis** [comment]
@markostanimirovic What do you mean? Shall I contribute and resolve this issue?

**Comment by markostanimirovic** [comment]
@Evexis Yes, if you want of course.

**Comment by Evexis** [comment]
@markostanimirovic I will try 😄

**Comment by Evexis** [comment]
@markostanimirovic [PR](https://github.com/ngrx/platform/pull/3227) I have an issue with tests failing, there are errors thrown from files not affected by my change. Could you help me?

**Comment by markostanimirovic** [comment]
Thanks for the PR! Sure, I'll take a look 👍

**Comment by marko-jobcloud** [comment]
@Evexis  can you rebase to `master` branch (not `angular-v13-rc`)?

**Comment by Evexis** [comment]
@marko-jobcloud done

**Comment by markostanimirovic** [comment]
@Evexis  but keep only your commit:

![ngrx-data](https://user-images.githubusercontent.com/17877290/141190479-6eb318cb-0752-4e39-a297-d8cbbf889ce1.PNG)

**Comment by Evexis** [comment]
@markostanimirovic Sorry for doing the mess, it's the first time I'm contributing - I've opened a new [PR](https://github.com/ngrx/platform/pull/3228) and have closed the first one

**Comment by tkitv** [comment]
As far as I see it, this behavior was intentional and should never have been changed. Now, the store never knows if all entities have been loaded or not, as the property gets set to true after the first successful call.
The only information you get now from this property is, that something has been loaded at some point.

**Comment by WojciechKasprzyk** [comment]
@tkitv Where were you when I was "fixing" it? xD

**Comment by smorandi** [comment]
> As far as I see it, this behavior was intentional and should never have been changed. Now, the store never knows if all entities have been loaded or not, as the property gets set to true after the first successful call.
> The only information you get now from this property is, that something has been loaded at some point.

yes exactely. we use ngrx also as data-cache, so that we dont alwayys have to call backend endpoint again and again for data we already have loaded. thats when we used the loaded$ observable.when it was set we knew tat at some pont „somebody“ requests ALL the data from a certain endpoint and dont have to load it again…unless forced to (e.g. a forced reload).
so i think a curent workaround could be to have a custom colection class which provides an „allLoaded“ observable in case the „load“ function has been called and data has been retrieved from the backend…
