### ISSUE TITLE
Error when compiling with option "strict: true" (nightly build)

### ISSUE THREAD

**Issue by mxth** [ngrx/platform#33]
node_modules/@ngrx/store/src/state.d.ts (20,68): Type 'StateActionPair<T, V> | undefined' has no property 'state' and no string index signature.
When I add the option `"strictNullChecks": false`, the error goes away.

**Comment by jinder** [comment]
Still seeing this in the latest nightly.

**Comment by jinder** [comment]
This is due to the parameter destructuring, and I've fixed it with the following:

```typescript
export type StateActionPair<T, V extends Action = Action> = { state: T | undefined, action?: V };
export function reduceState<T, V extends Action = Action>(
  stateActionPair: StateActionPair<T, V> = { state: undefined },
  [ action, reducer ]: [ V, ActionReducer<T, V> ]
): StateActionPair<T, V> {
  const { state } = stateActionPair;
  return { state: reducer(state, action), action };
}
```

It's caused by the fact that the parameter is possibly undefined (because there's a default assignment), and therefore the destructuring isn't safe as the type definition is `StateActionPair<T, V> | undefined`.  

An alternative approach is to remove the default assignment:

```typescript
export type StateActionPair<T, V extends Action = Action> = { state: T | undefined, action?: V };
export function reduceState<T, V extends Action = Action>(
  { state }: StateActionPair<T, V>,
  [ action, reducer ]: [ V, ActionReducer<T, V> ]
): StateActionPair<T, V> {
  return { state: reducer(state, action), action };
}
```

Sorry I can't submit a PR.  Corporate firewalls!
