### ISSUE TITLE
@ngrx/entity ???

### ISSUE THREAD

**Issue by mailok** [ngrx/platform#350]
please, where I find some documentacion about @ngrx/entity ??
How to use, some example.

**Comment by jotatoledo** [comment]
https://github.com/ngrx/platform/pull/328

**Comment by eabassey** [comment]
Checkout the reference implementation for @ngrx/store at: https://github.com/ngrx/platform/blob/master/example-app/app/books/reducers/books.ts

**Comment by loiane** [comment]
I updated my example to use entity as well: https://github.com/loiane/angular-ngrx4-example/tree/master/src/app (still need to refactor and improve a few things, but basic functionality is there already).

**Comment by PrivateMeggido** [comment]
Is there a planned date for releasing this in npm repositories proper? Currently using the git reference, but looking forward to the package publish. Thanks for doing this great work, helps out a lot with the type driven approach.

**Comment by Lonli-Lokli** [comment]
@loiane , I thought findById should be implemented via EntityState?
  findById(record: { id }) {
    return this.getTasks()[record['id']];
  }

**Comment by eabassey** [comment]
FindById() will not be bad but will not be used if implemented via EntityState<T>. It will have to end up being used in a reducer function which in that case will not be a pure function anymore. The simplicity of the entityAdapter takes care of that so that it can be used in the reducers without any hussle.
It will also prevent the trouble of implementing findById() for each Entity Model in your project (think of 100 models.."It won't be DRY").
