### ISSUE TITLE
[signals] getState function should return computed values too

### ISSUE THREAD

**Issue by jits** [ngrx/platform#4143]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

@markostanimirovic – our implementation in #4118 may have been incomplete — it only outputs the "base" state and not computed values. My suggestion would be to also include the computed signal values in the output. I'm happy to make a PR if you agree.

**Reproduction:**

https://stackblitz.com/edit/stackblitz-starters-ixta5f?file=src%2Fmain.ts

In the StackBlitz above you can see a signal store defined with a `value` field and a computed `double` signal. But in the output of the `getState` we only see `value`.

### Expected behavior

The current values of computed fields should be in the output of the `getState` helper function.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: v17
NgRx: v17.0.0

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment]
Hi @jits,

This is not the bug, it works as intended. The `getState` function should return only the (base) state.

Out of curiosity, can you provide an example where it would be useful to get the dictionary of computed values?

**Comment by jits** [comment]
@markostanimirovic –

> Out of curiosity, can you provide an example where it would be useful to get the dictionary of computed values?

Yes, of course. My main use case right now is being able to log whenever any state changes, with the following:

```ts
withHooks({
  onInit(store) {
    effect(() => console.log('State:', getState(store)));
  }
})
```

And, in general, it always felt awkward to me in NgRx Store and ComponentStore that you couldn't easily get a snapshot of the _whole_ state, including all derived values (which I strongly consider to be a part of the overall state) — we encourage folks to use computed/derived values wherever possible so it would useful (IMO) to be able to have a very easy way of saying "give me the full state of this store as it is right now".

Having said that, for my specific use case of logging/tracing, I recall there being some discussions about integration with the Redux DevTools (or perhaps some other approach) — that would solve this particular need right now.

**Comment by markostanimirovic** [comment]
If you specifically need this feature somewhere, you can implement a custom function that takes a store and returns the values of all its signals as a single object. However, this will not be part of the core library for the following reasons:

- For synchronization with local or any other storage, the derived state should not be persisted. The derived state is always re-computed based on the base state.
- This behavior of the `getState` function would also cause a problem if someone wants to make a Redux Devtools plugin for the SignalStore because again - only the base state should be connected.
- The Signal/ComponentStore can contain computed signals/selectors that are calculated from the base/computed state from multiple stores, not only from the base state of that store.

**Comment by jits** [comment]
@markostanimirovic – that makes sense. Thanks for providing that context.

(Just thinking out loud…) It seems there's at least 3 levels of state we can reason about:

1. the base state — can be set and persisted
1. the derived state — never set directly nor persisted
1. the combination of base and derived state — representing ALL the state within the store

It makes sense that the core library of NgRx doesn't need to provide anything extra for (3) — that is probably an application / userland concern.
