### ISSUE TITLE
@ngrx/signals: add `deepComputed` function

### ISSUE THREAD

**Issue by JulienLecoq** [ngrx/platform#4202]
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

I would like to have a ``computed()`` function similar to the one provided by Angular for ``Signals`` but in this case, instead of returning a Signal, it would return a ``DeepSignal``.

This would allow to optimise template rendering for computed states based on objects.

Exemples:

- Current way of using computed variables:
```html
<p>
    {{ computedState().firstName }}
</p>
```
- Proposed way of using computed variables:
```html
<p>
    {{ computedState.firstName() }}
</p>
```

### Describe any alternatives/workarounds you're currently using

I'm using the ``computed()`` function provided by Angular which returns a Signal.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Unless I'm mistaken on your request, then is what the `signalState` function does.

https://ngrx.io/guide/signals/signal-state

**Comment by JulienLecoq** [comment]
No, ``signalState`` creates a "deep" signal typed as ``SignalState``.
What I would like to have is the ability to get a computed deep signal.

For signals we have:

```ts
count = signal(0)

doubleCount = computed(() => {
    return this.count() * 2
})
```

I would like the same but for deep signals, so something like:

```ts
count = signal(0)

doubleCount = computedState(() => {
    return this.count() * 2
})
```

Hence, ``doubleCount`` would be a ``SignalState`` instead of a ``Signal``.

For primitives, this isn't very useful. But this would be useful for non-primitive values.

**Comment by JulienLecoq** [comment]
Right know, you can only have signals when using ``computed()``, which give you this when using it:

```html
<p>
    {{ computedSignal().firstName }}
</p>
```

Whereas with a deep signal that you could get with ``computedState()``, you could do:
```html
<p>
    {{ computedSignalState.firstName() }}
</p>
```

Which is better for template rendering.

**Comment by markostanimirovic** [comment]
We already considered this feature some time ago - `deepComputed`: 

```ts
const counts = signalState({ count1: 1, count2: 2 });

const doubleCounts = deepComputed(() => ({
  count1: counts.count1() * 2,
  count2: counts.count2() * 2,
});


console.log(doubleCounts()); // { count1: 2, count2: 4 }
console.log(doubleCounts.count1()); // 2
console.log(doubleCounts.count2()); // 4
```

**Comment by JulienLecoq** [comment]
Cool, what was the result of this consideration?

Btw, if it is introduced later on in the library with the name ``deepComputed``, wouldn't it make sense to rename ``signalState`` to ``deepSignal``? Maybe it's just me, but I find the name ``deepSignal`` more descriptive than ``signalState``. I myself created a wrapper around signalState so that it's called deepSignal when I use it haha.

**Comment by ducin** [comment]
@JulienLecoq  I get the idea that the API is different and you like it more, but I'm not sure what problem are you trying to solve here. Since computeds are cached anyway, don't think perf could make much difference here.

Especially in this section:

> Describe any alternatives/workarounds you're currently using
>
>> I'm using the computed() function provided by Angular which returns a Signal.

In what way would the proposed `deepComputed` be better?

IMO the fact that e.g. the store itself is NOT a signal, or that we've got DeepSignals, etc. - all these are implementation details. The wonderful thing in the signal store design is its simplicity. By exposing additional `withDeepComputed` (or whatever) the complexity gets higher. It appears as an abstraction leak to me.

Currently the fact that `signalStore` creates deep signals is hidden behind a proxy. And thanks to precise typing, you can easily use those deep signals without even knowing how all those things work. You can't decide directly whether a piece in signal store is a DeepSignal vs Signal (correct me @markostanimirovic if I'm mistaken). IMO encapsulating computed vs DeepComputed makes a better approach - as it doesn't leak abstraction.

**Comment by Maransatto** [comment]
@ducin 
Here is a scenario where `withDeepComputed` would be useful:

I have a `RecipeStore` which is a `SignalStore` as the root store.
Then I also have a `withControlPoints()` function to get a `signalStoreFeature()` and that adds to the root state an attribute `controlPoints`. But if you look at the RecipeStore attributes from their initial state, they are all `DeepSignals`, while the attributes derived from the computed `signalStoreFeatured` are regular signals.

In the end, when we access the store from a component, we see all the attributes, but some of them are `deepSignals` (from the initial state)  while others are regular Signals (from computed). This is confusing.

The ideal would be to return DeepSignals when using `withComputed()` by default.
