### ISSUE TITLE
Type 'Unsubscribable' must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by draylegend** [ngrx/platform#4285]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

```js
✘ [ERROR] NG8: Type 'Unsubscribable' must have a '[Symbol.iterator]()' method that returns an iterator. [plugin angular-compiler]

    src/main.ts:117:12:
      117 │   @for(c of characters(); track c.id){
          ╵             ~~~~~~~~~~
```

[Stackblitz](https://stackblitz.com/edit/draylegend-ngrx-signal-store-entities-interation-issue?file=src%2Fmain.ts)

### Expected behavior

Should iterate over signal array, created by `setAllEntities(entitiesArray, {collection: 'collectionName')`

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

See [`package.json`](https://stackblitz.com/edit/draylegend-ngrx-signal-store-entities-interation-issue?file=package.json&view=editor)

**Comment by alexkunin** [comment]
I think this is the problem (removed all irrelevant parts):
```ts
const withEntitiesStore = (
  collection: string,
) =>
  signalStoreFeature(
    withMethods(s => ({
      ['load' + fcUpper(collection)]: rxMethod<void>(
        // ...
      ),
    }))
  );
```
So, method name is dynamic string, result of an expression, and you know it's a single method, but TypeScript sees `{ [key: string]: rxMethod<void> }` (i.e. widens the type to `Record<string, RxMethod<void>>`), and then somewhere inside `withMethods` (my guess) all other properties of the store object are overridden due to this very wide type.

Because of this, `characters` has type `RxMethod<void>`, and thus `characters()` is `Unsubscribable` instead of `Signal<Character[]>`.

**Comment by timdeschryver** [comment]
See @alexkunin 's answer.
We try to keep issues for feature requests and bug reports.
I'm closing this issue because I don't think this issue does not fall under these categories.
