### ISSUE TITLE
Argument type Prettify<StateSignals..... is not assignable to parameter type WritableStateSource<object> 

### ISSUE THREAD

**Issue by apushnev** [ngrx/platform#4560]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

`import { patchState, signalStore, withMethods, withState } from '@ngrx/signals';

type LanguageState = {
  selectedLanguage: number;
};

const initialState: LanguageState = {
  selectedLanguage: 0,
};

export const LanguageStore = signalStore(
  { providedIn: 'root' },
  withState(initialState),
  withMethods((store) => ({
    setLanguage(lang: number) {
      patchState(store, { selectedLanguage: lang });
    },
  }))
);`

I have some strange error with type
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/d75b02ca-ae5a-4397-9a7a-314eec56764b">

UPD:
With VSCode works fine.
<img width="786" alt="image" src="https://github.com/user-attachments/assets/97c4b55f-ebb3-4a2d-b008-6a730d9bb1b1">

### Expected behavior

It should work without errors

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)
WebStorm 2023.3.6
NgRx: ^18.1.0
Angular: ~18.2.0
Node: 22.0.0
typescript: ~5.5.2

### Other information

I'm using "@ngrx/signals": "^18.1.0"

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [X] No

**Comment by markostanimirovic** [comment]
This issue is out of our scope since we're not maintaining the TypeScript Language Server for JetBrains IDEs.

There are many issues in WebStorm when it comes to advanced TypeScript. However, I haven't noticed that it doesn't work in simple examples such as this one. Try restarting the IDE, upgrading to the latest version, or reporting this issue to their support.
