### ISSUE TITLE
Should i store all variables of the components in store ?

### ISSUE THREAD

**Issue by trinhvanhuy** [ngrx/platform#465]
Hello everyone  , this is not an issue
I use Angular 4 with ngrx, I've stored most of variables, properties that i fetch from server ...   
I wonder that should be better if i store all variable ( like: graph data of chartjs, toogle show/hide of an element, ... ) i mean, all of variables of the components should be stored in reducer ? and why it's better / worse  
Thanks so much

**Comment by phillipzada** [comment]
Hi @trinhvanhuy, 

If you want to use the 1st principal of the redux pattern as a guideline rather than writ (http://redux.js.org/docs/introduction/ThreePrinciples.html#single-source-of-truth) then the rule of thumb we follow is, "if you need to save/export the state and open the app in the exact state what data do you need in the state".

**Comment by trinhvanhuy** [comment]
sometime i hage a variable like this :  isShowHeaderBar: boolean , this is a variable for show/hide header , and I have a button for changing that variable, should i store it in state ? and use action, dispatcher for the button show/hide ? 
also, I want to know if i should store as much as i can in state or only something MUST store in state ( may be state sigleton will slowdown the application ?

**Comment by brandonroberts** [comment]
@trinhvanhuy its up to you what to determine to store whether it be for global availability or rehydration of state. If you need further assistance, please use the support channel: https://gitter.im/ngrx/platform
