### ISSUE TITLE
[Feature Request] Export a Reducer type

### ISSUE THREAD

**Issue by michaeljota** [ngrx/platform#884]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
It does not seems like we have a type or an interface for reducers, and if this have something like that, it's not documented properly, or I haven't found it.

## Expected behavior:

A simple type declaration about the shape that a reducer have to be. Something like
```typescript
type Reducer<S, A extends Action = Action> = (state: S, action: A) => S;
// Or with an interface
interface Reducer<S, A extends Action = Action> {
  (state: S, action: A): S;
}
```

I'm sorry if this is something ngrx currently have, but I could not find it. If it have it, please, let me know from how to import it. Thanks you.

**Comment by brandonroberts** [comment]
This interface is already exported from Store as an `ActionReducer`. You don't have to explicitly define it in your reducer map because of the `ActionReducerMap` interface.

https://github.com/ngrx/platform/blob/master/modules/store/src/models.ts#L9
https://github.com/ngrx/platform/blob/master/modules/store/src/index.ts#L3
