### ISSUE TITLE
ngrx-entity equivalent for wrapping API requests

### ISSUE THREAD

**Issue by JNaftali** [ngrx/platform#939]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Currently if you want to use ngrx effects to wrap an API request there are repetitive `StartRequest`, `RequestSuccess`, and `RequestError` actions, reducers, and effects:
* `StartRequest`
  * An effect calls the appropriate method, probably from an ApiService. Depending on how it resolves make a new `RequestSuccess` or `RequestError` action with the results
  * A reducer sets some piece of state that says `loading: true`
* `RequestSuccess`
  * A reducer stores (possibly after transforming) the results of the API call somewhere.
  * Same reducer also sets `loading` state to `false`
* `RequestError`
  * A reducer stores the error details somewhere so they can be displayed to the user
  * Same reducer also sets `loading` state to `false`

## Expected behavior:
This pattern is common enough that I think users would benefit from an ngrx-entity-like library that abstracts away the most common behavior and exposes hooks for users to customize when necessary.

## Other information:
A possibly similar userland project are the async actions creators in https://github.com/aikoven/typescript-fsa (which I've used to good effect in the past when using Redux/TS/effects in React projects)

I've never contributed to ngrx before, and this seems like a big thing to work on. But given interest and guidance I'd be willing to work on it in my free time if the maintainers think that would be appropriate. Also, thanks for all the cool stuff that IS in ngrx already!

**Comment by brandonroberts** [comment]
You should take a look at [ngrx-data](https://github.com/johnpapa/angular-ngrx-data) which provides a convention-based way of handling API requests for common entities. Its using `@ngrx/entity` under the hood also.

**Comment by JNaftali** [comment]
Thanks for the heads up!

**Comment by dalu** [comment]
It is very limited and opinionated.

Data is a first class citizen, I don't know why it's handled the way it is in ngrx.
In ngrx communicating with a http api is an effect. Ludicrous.
There is no comprehensive example app. Anything useful is behind a paywall.
Memory being allocated altough it's not necessary.
It's insane.
This ngrx is something for long lived data. But how long does an app live in the browser?
It's the same insanity a few years ago the newcomers would bring "OO" to PHP.
It's not even lightweight.
It doesn't even support start and limit.
It has zero garbage collection.
EVERYTHING inside me screams STAY AWAY.
This is the 2nd day I wasted on this crap. Idk why I'm bothering with this.
The real reason is because Angular and its change detection fucking blows.
And you need those abominations of a construct that ngrx is.

**Comment by danilohgds** [comment]
@dalu
Maybe you should spend more time understanding the patterns behind ngrx/redux and why they came to be before criticizing an approach.

Any interaction with the environment, logs, api calls, localstorage, everything is deemed to be a side effect. Things are done for a matter of control, standardization and more importantly, traceability. 

Perhaps 2 days aren't enough to understand a library that was put together from a pattern that took years to fully develop. Might wanna enhance your knowledge before ranting off without any real reason to.
